name: Bigbrother CICD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alanx30/ecommercemodulo_consumer:${{ github.sha }}
    - name: push the Docker image
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }} && docker push alanx30/ecommercemodulo_consumer:${{ github.sha }}

# Set up the Kubernetes CLI with your DigitalOcean Kubernetes cluster.
    - name: Set up kubectl
      uses: matootie/dokube@v1.4.0
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: omnixapi
    - name: Get nodes
      run: kubectl get nodes

    - name: Set images
      run: kubectl set image deployment/consumer consumer=alanx30/ecommercemodulo_consumer:${{ github.sha }}